"""Enums for the task scheduler module."""

import enum


class RoutingLabel(enum.Enum):
  """Labels for task routing."""

  PI_PORTAL_CONTROL = "PI_PORTAL_CONTROL"
  ARCHIVAL = "ARCHIVAL"
  CAMERA = "CAMERA"
  CHAT_SEND_MESSAGE = "CHAT_SEND_MESSAGE"
  CHAT_UPLOAD_SNAPSHOT = "CHAT_UPLOAD_SNAPSHOT"
  CHAT_UPLOAD_VIDEO = "CHAT_UPLOAD_VIDEO"
  FILE_SYSTEM = "FILE_SYSTEM"
  SUPERVISOR_PROCESS = "SUPERVISOR_PROCESS"


class TaskType(enum.Enum):
  """Pi Portal schedulable task types."""

  BASE = "BASE"
  ARCHIVE_LOGS = "ARCHIVE_LOGS"
  ARCHIVE_VIDEOS = "ARCHIVE_VIDEOS"
  CAMERA_SNAPSHOT = "CAMERA_SNAPSHOT"
  CHAT_SEND_MESSAGE = "CHAT_SEND_MESSAGE"
  CHAT_SEND_TEMPERATURE_READING = "CHAT_SEND_TEMPERATURE_READING"
  CHAT_UPLOAD_SNAPSHOT = "CHAT_UPLOAD_SNAPSHOT"
  CHAT_UPLOAD_VIDEO = "CHAT_UPLOAD_VIDEO"
  FILE_SYSTEM_COPY = "FILE_SYSTEM_COPY"
  FILE_SYSTEM_MOVE = "FILE_SYSTEM_MOVE"
  FILE_SYSTEM_REMOVE = "FILE_SYSTEM_REMOVE"
  FLAG_SET_VALUE = "FLAG_SET_VALUE"
  NON_SCHEDULED = "NON_SCHEDULED"
  QUEUE_MAINTENANCE = "QUEUE_MAINTENANCE"
  SUPERVISOR_PROCESS = "SUPERVISOR_PROCESS"


class TaskManifests(enum.Enum):
  """Manifests for task inventorying."""

  FAILED_TASKS = "FAILED_TASKS"
