---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    pre_create_environment:
      - pip install poetry
    post_install:
      - pip uninstall -y sphinx
      - poetry env use python && POETRY_VIRTUALENV="$(poetry env info --path)" && rm -rf "${POETRY_VIRTUALENV}" && ln -sf "${READTHEDOCS_VIRTUALENV_PATH}" "${POETRY_VIRTUALENV}"
      - poetry install

sphinx:
  builder: html
  fail_on_warning: false
  configuration: documentation/source/conf.py
