---
version: "3"

services:
  pi_portal:
    build:
      args:
        BUILD_ARG_PIP_INDEX_URL: "https://pypi.org/simple"
        BUILD_ARG_PLATFORM: "amd64"
      context: .
      dockerfile: assets/Dockerfile
    platform: linux/amd64
    env_file:
      - assets/local.env
    environment:
      ENVIRONMENT: "DEVELOPMENT"
    volumes:
      - ${HOME}/.ssh:/home/user/.ssh
      - ${HOME}/.gitconfig:/home/user/.gitconfig
      - ${HOME}/.gitconfig_global:/home/user/.gitconfig_global
      - ./:/app
