---
version: "3"

services:

  armv7-prebuild:
    image: armv7-prebuild
    build:
      args:
        BUILD_ARG_PIP_INDEX_URL: "https://piwheels.org/simple"
        BUILD_ARG_PLATFORM: "armv7"
        BUILD_ARG_PYTHON_VERSION: "3.9"
      context: ../..
      dockerfile: ./assets/Dockerfile
    platform: linux/arm/v7
    volumes:
      - ../..:/app

  armv7:
    build:
      args:
        BUILD_ARG_PIP_INDEX_URL: "https://piwheels.org/simple"
        BUILD_ARG_PLATFORM: "armv7"
        BUILD_ARG_PYTHON_VERSION: "3.9"
      context: ../..
      dockerfile: ./packaging/debian/assets/Dockerfile
    command: ./packaging/debian/assets/container_init.sh
    platform: linux/arm/v7
    env_file:
      - ../../assets/local.env
    environment:
      DEB_BUILD_ARCH: "armhf"
      DEBPATH: "build_armhf"
      DISTPATH: "dist_armhf"
      ENVIRONMENT: "PACKAGE"
      PIP_INDEX_URL: "https://piwheels.org/simple"
    volumes:
      - ../..:/app

  arm64-prebuild:
    image: arm64-prebuild
    build:
      args:
        BUILD_ARG_PIP_INDEX_URL: "https://pypi.org/simple"
        BUILD_ARG_PLATFORM: "arm64"
        BUILD_ARG_PYTHON_VERSION: "3.9"
      context: ../..
      dockerfile: ./assets/Dockerfile
    platform: linux/arm64
    volumes:
      - ../..:/app

  arm64:
    build:
      args:
        BUILD_ARG_PIP_INDEX_URL: "https://pypi.org/simple"
        BUILD_ARG_PLATFORM: "arm64"
        BUILD_ARG_PYTHON_VERSION: "3.9"
      context: ../..
      dockerfile: ./packaging/debian/assets/Dockerfile
    command: ./packaging/debian/assets/container_init.sh
    platform: linux/arm64
    env_file:
      - ../../assets/local.env
    environment:
      DEB_BUILD_ARCH: "arm64"
      DEBPATH: "build_arm64"
      DISTPATH: "dist_arm64"
      ENVIRONMENT: "PACKAGE"
      PIP_INDEX_URL: "https://pypi.org/simple"
    volumes:
      - ../..:/app
