---
version: "3"

services:

  armv7:
    build:
      args:
        BUILD_ARG_GOARCH: "arm"
        BUILD_ARG_GOARM: "7"
        BUILD_ARG_GOOS: "linux"
      context: .
      dockerfile: assets/Dockerfile
    command: cp /usr/bin/filebeat /mnt/bin/filebeat-armv7
    platform: linux/arm/v7
    volumes:
      - ./bin:/mnt/bin

  arm64:
    build:
      args:
        BUILD_ARG_GOARCH: "arm64"
        BUILD_ARG_GOARM: ""
        BUILD_ARG_GOOS: "linux"
      context: .
      dockerfile: assets/Dockerfile
    command: cp /usr/bin/filebeat /mnt/bin/filebeat-arm64
    platform: linux/arm64
    volumes:
      - ./bin:/mnt/bin
