#!/bin/bash

set -eo pipefail

PACKAGE_USER="pi_portal"

groups() {
  if grep -q gpio /etc/group; then
    usermod -a -G gpio "${PACKAGE_USER}"
  fi
  if grep -q video /etc/group; then
    usermod -a -G video "${PACKAGE_USER}"
  fi
}

permissions() {
  local FILEPATH

  FILEPATH_LIST=("/opt/venvs/pi_portal" "/usr/bin/filebeat" "/usr/bin/portal" "/var/lib/motion")

  for FILEPATH in "${FILEPATH_LIST[@]}"; do
    chown -R "${PACKAGE_USER}":"${PACKAGE_USER}" "${FILEPATH}"
  done
}

users() {
  if ! id -u "${PACKAGE_USER}" &>/dev/null; then
    useradd -r -s /usr/sbin/nologin --no-create-home "${PACKAGE_USER}"
  fi
}

main() {
  users
  groups
  permissions
}

main "$@"
